[functions]
directory = "functions"
node_bundler = "esbuild"
included_files =  ["functions/templates/*"]
external_node_modules = ["dotenv","ejs","nodemailer","node-fetch","sanitize-html"]

[[redirects]]
from = "/roboflair/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true